/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 146
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment_multi = 1,
  sym_comment_line = 2,
  sym_integer = 3,
  sym_float = 4,
  anon_sym_true = 5,
  anon_sym_false = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_string_token1 = 8,
  aux_sym_enum_token1 = 9,
  sym_custom_enum = 10,
  anon_sym_POUND = 11,
  aux_sym_directive_token1 = 12,
  anon_sym_LF = 13,
  anon_sym_LT = 14,
  aux_sym_absolute_path_token1 = 15,
  anon_sym_GT = 16,
  aux_sym_relative_path_token1 = 17,
  anon_sym_DASH = 18,
  anon_sym_COLON_COLON = 19,
  anon_sym_LBRACK = 20,
  anon_sym_COMMA = 21,
  anon_sym_RBRACK = 22,
  anon_sym_COLON = 23,
  anon_sym_DOLLAR = 24,
  anon_sym_struct = 25,
  anon_sym_LBRACE = 26,
  anon_sym_RBRACE = 27,
  anon_sym_expr = 28,
  anon_sym_LBRACE_LBRACE = 29,
  anon_sym_RBRACE_RBRACE = 30,
  anon_sym_EQ = 31,
  sym_alias_operator = 32,
  anon_sym_SLASH_GT = 33,
  anon_sym_LT_SLASH = 34,
  sym_source_file = 35,
  sym_boolean = 36,
  sym_string = 37,
  sym_enum = 38,
  sym_directive = 39,
  sym_absolute_path = 40,
  sym_relative_path = 41,
  sym_constant = 42,
  sym_identifier = 43,
  sym_bind_operator = 44,
  sym_full_type_identifier = 45,
  sym_list = 46,
  sym_field_value = 47,
  sym_field = 48,
  sym_fields = 49,
  sym_struct_impl_keyword = 50,
  sym_struct_impl = 51,
  sym_expr_impl_keyword = 52,
  sym_expr_impl = 53,
  sym_impl_operator = 54,
  sym_impl_ref = 55,
  sym_expr = 56,
  sym_struct = 57,
  sym_attribute_value = 58,
  sym_attribute = 59,
  sym_alias = 60,
  sym_empty_tag = 61,
  sym_tag = 62,
  sym_element = 63,
  aux_sym_source_file_repeat1 = 64,
  aux_sym_full_type_identifier_repeat1 = 65,
  aux_sym_list_repeat1 = 66,
  aux_sym_fields_repeat1 = 67,
  aux_sym_empty_tag_repeat1 = 68,
  aux_sym_tag_repeat1 = 69,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment_multi] = "comment_multi",
  [sym_comment_line] = "comment_line",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_enum_token1] = "enum_token1",
  [sym_custom_enum] = "custom_enum",
  [anon_sym_POUND] = "#",
  [aux_sym_directive_token1] = "directive_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_LT] = "<",
  [aux_sym_absolute_path_token1] = "absolute_path_token1",
  [anon_sym_GT] = ">",
  [aux_sym_relative_path_token1] = "relative_path_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_expr] = "expr",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_EQ] = "=",
  [sym_alias_operator] = "alias_operator",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [sym_source_file] = "source_file",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_enum] = "enum",
  [sym_directive] = "directive",
  [sym_absolute_path] = "absolute_path",
  [sym_relative_path] = "relative_path",
  [sym_constant] = "constant",
  [sym_identifier] = "identifier",
  [sym_bind_operator] = "bind_operator",
  [sym_full_type_identifier] = "full_type_identifier",
  [sym_list] = "list",
  [sym_field_value] = "field_value",
  [sym_field] = "field",
  [sym_fields] = "fields",
  [sym_struct_impl_keyword] = "struct_impl_keyword",
  [sym_struct_impl] = "struct_impl",
  [sym_expr_impl_keyword] = "expr_impl_keyword",
  [sym_expr_impl] = "expr_impl",
  [sym_impl_operator] = "impl_operator",
  [sym_impl_ref] = "impl_ref",
  [sym_expr] = "expr",
  [sym_struct] = "struct",
  [sym_attribute_value] = "attribute_value",
  [sym_attribute] = "attribute",
  [sym_alias] = "alias",
  [sym_empty_tag] = "empty_tag",
  [sym_tag] = "tag",
  [sym_element] = "element",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_full_type_identifier_repeat1] = "full_type_identifier_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
  [aux_sym_empty_tag_repeat1] = "empty_tag_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment_multi] = sym_comment_multi,
  [sym_comment_line] = sym_comment_line,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_enum_token1] = aux_sym_enum_token1,
  [sym_custom_enum] = sym_custom_enum,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_absolute_path_token1] = aux_sym_absolute_path_token1,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_relative_path_token1] = aux_sym_relative_path_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_expr] = anon_sym_expr,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_alias_operator] = sym_alias_operator,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_source_file] = sym_source_file,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_enum] = sym_enum,
  [sym_directive] = sym_directive,
  [sym_absolute_path] = sym_absolute_path,
  [sym_relative_path] = sym_relative_path,
  [sym_constant] = sym_constant,
  [sym_identifier] = sym_identifier,
  [sym_bind_operator] = sym_bind_operator,
  [sym_full_type_identifier] = sym_full_type_identifier,
  [sym_list] = sym_list,
  [sym_field_value] = sym_field_value,
  [sym_field] = sym_field,
  [sym_fields] = sym_fields,
  [sym_struct_impl_keyword] = sym_struct_impl_keyword,
  [sym_struct_impl] = sym_struct_impl,
  [sym_expr_impl_keyword] = sym_expr_impl_keyword,
  [sym_expr_impl] = sym_expr_impl,
  [sym_impl_operator] = sym_impl_operator,
  [sym_impl_ref] = sym_impl_ref,
  [sym_expr] = sym_expr,
  [sym_struct] = sym_struct,
  [sym_attribute_value] = sym_attribute_value,
  [sym_attribute] = sym_attribute,
  [sym_alias] = sym_alias,
  [sym_empty_tag] = sym_empty_tag,
  [sym_tag] = sym_tag,
  [sym_element] = sym_element,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_full_type_identifier_repeat1] = aux_sym_full_type_identifier_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
  [aux_sym_empty_tag_repeat1] = aux_sym_empty_tag_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_multi] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_custom_enum] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_absolute_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_relative_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_expr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_alias_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_absolute_path] = {
    .visible = true,
    .named = true,
  },
  [sym_relative_path] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bind_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_full_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_impl_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_impl_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_impl_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_impl_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_full_type_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_empty_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bind = 1,
  field_close_tag = 2,
  field_empty_tag = 3,
  field_field_identifier = 4,
  field_field_value = 5,
  field_fields = 6,
  field_identifier = 7,
  field_module = 8,
  field_name = 9,
  field_open_tag = 10,
  field_type = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bind] = "bind",
  [field_close_tag] = "close_tag",
  [field_empty_tag] = "empty_tag",
  [field_field_identifier] = "field_identifier",
  [field_field_value] = "field_value",
  [field_fields] = "fields",
  [field_identifier] = "identifier",
  [field_module] = "module",
  [field_name] = "name",
  [field_open_tag] = "open_tag",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 1},
  [11] = {.index = 16, .length = 3},
  [12] = {.index = 19, .length = 2},
  [13] = {.index = 21, .length = 2},
  [14] = {.index = 23, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_empty_tag, 1},
  [3] =
    {field_module, 0},
    {field_type, 1},
  [5] =
    {field_name, 1},
    {field_value, 2},
  [7] =
    {field_identifier, 0},
    {field_value, 2},
  [9] =
    {field_close_tag, 4},
    {field_open_tag, 1},
  [11] =
    {field_bind, 3},
    {field_identifier, 1},
  [13] =
    {field_close_tag, 5},
    {field_open_tag, 1},
  [15] =
    {field_identifier, 1},
  [16] =
    {field_bind, 3},
    {field_fields, 5},
    {field_identifier, 1},
  [19] =
    {field_field_identifier, 0},
    {field_field_value, 2},
  [21] =
    {field_close_tag, 6},
    {field_open_tag, 1},
  [23] =
    {field_close_tag, 7},
    {field_open_tag, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 22,
  [34] = 30,
  [35] = 23,
  [36] = 36,
  [37] = 31,
  [38] = 32,
  [39] = 24,
  [40] = 28,
  [41] = 36,
  [42] = 29,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 48,
  [69] = 61,
  [70] = 70,
  [71] = 71,
  [72] = 53,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 71,
  [77] = 77,
  [78] = 70,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 63,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 64,
  [102] = 77,
  [103] = 66,
  [104] = 62,
  [105] = 67,
  [106] = 49,
  [107] = 60,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 112,
  [132] = 132,
  [133] = 113,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 130,
  [145] = 132,
};

static const TSCharacterRange sym_custom_enum_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '+'}, {'-', '.'}, {'0', '<'}, {'?', 'Z'}, {'\\', '\\'},
  {'^', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 50,
        '#', 67,
        '$', 90,
        ',', 87,
        '-', 84,
        '/', 4,
        ':', 89,
        '<', 71,
        '=', 99,
        '>', 77,
        '@', 100,
        '[', 86,
        ']', 88,
        'e', 26,
        'f', 12,
        's', 23,
        't', 18,
        '{', 93,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '<') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 50,
        '-', 65,
        '/', 3,
        '[', 86,
        ']', 88,
        'f', 56,
        't', 60,
        '{', 93,
        '}', 94,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '-' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '>') ADVANCE(101);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '>') ADVANCE(77);
      if (lookahead == '@') ADVANCE(100);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(85);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 'x') ADVANCE(17);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(98);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '#', 67,
        '$', 90,
        ',', 87,
        '-', 83,
        '/', 4,
        ':', 89,
        '<', 70,
        '=', 99,
        '>', 77,
        '@', 100,
        ']', 88,
        '{', 92,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment_multi);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment_multi);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment_multi);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment_multi);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment_line);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '>') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(51);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'a') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'l') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'r') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'u') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_custom_enum);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_custom_enum);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 11, lookahead))) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(102);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '*') ADVANCE(75);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '/') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '*') ADVANCE(78);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '/') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_expr);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_alias_operator);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 28},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 28},
  [25] = {.lex_state = 28},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 28},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 28},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 28},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 28},
  [46] = {.lex_state = 28},
  [47] = {.lex_state = 28},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 28},
  [50] = {.lex_state = 28},
  [51] = {.lex_state = 28},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 28},
  [54] = {.lex_state = 28},
  [55] = {.lex_state = 28},
  [56] = {.lex_state = 28},
  [57] = {.lex_state = 28},
  [58] = {.lex_state = 28},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 28},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 28},
  [63] = {.lex_state = 28},
  [64] = {.lex_state = 28},
  [65] = {.lex_state = 28},
  [66] = {.lex_state = 28},
  [67] = {.lex_state = 28},
  [68] = {.lex_state = 28},
  [69] = {.lex_state = 28},
  [70] = {.lex_state = 28},
  [71] = {.lex_state = 28},
  [72] = {.lex_state = 28},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 28},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 28},
  [77] = {.lex_state = 28},
  [78] = {.lex_state = 28},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 28},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 28},
  [84] = {.lex_state = 28},
  [85] = {.lex_state = 28},
  [86] = {.lex_state = 28},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 28},
  [89] = {.lex_state = 28},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 28},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 28},
  [96] = {.lex_state = 28},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 28},
  [99] = {.lex_state = 28},
  [100] = {.lex_state = 28},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 28},
  [109] = {.lex_state = 28},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 9},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 28},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 28},
  [121] = {.lex_state = 28},
  [122] = {.lex_state = 54},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 28},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 8},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 8},
  [135] = {.lex_state = 10},
  [136] = {.lex_state = 6},
  [137] = {.lex_state = 2},
  [138] = {.lex_state = 28},
  [139] = {.lex_state = 2},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 1},
  [143] = {.lex_state = 1},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment_multi] = ACTIONS(3),
    [sym_comment_line] = ACTIONS(3),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_expr] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_alias_operator] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(111),
    [sym_directive] = STATE(6),
    [sym_struct_impl_keyword] = STATE(99),
    [sym_struct_impl] = STATE(6),
    [sym_expr_impl_keyword] = STATE(100),
    [sym_expr_impl] = STATE(6),
    [sym_empty_tag] = STATE(64),
    [sym_tag] = STATE(64),
    [sym_element] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment_multi] = ACTIONS(3),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(88), 1,
      sym_attribute_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(13), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(84), 6,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_expr,
      sym_struct,
  [40] = 9,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(97), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(73), 4,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
  [75] = 9,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(97), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(73), 4,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
  [110] = 9,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_POUND,
    ACTIONS(38), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      anon_sym_DOLLAR,
    STATE(99), 1,
      sym_struct_impl_keyword,
    STATE(100), 1,
      sym_expr_impl_keyword,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(64), 2,
      sym_empty_tag,
      sym_tag,
    STATE(5), 5,
      sym_directive,
      sym_struct_impl,
      sym_expr_impl,
      sym_element,
      aux_sym_source_file_repeat1,
  [144] = 9,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(99), 1,
      sym_struct_impl_keyword,
    STATE(100), 1,
      sym_expr_impl_keyword,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(64), 2,
      sym_empty_tag,
      sym_tag,
    STATE(5), 5,
      sym_directive,
      sym_struct_impl,
      sym_expr_impl,
      sym_element,
      aux_sym_source_file_repeat1,
  [178] = 8,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    STATE(87), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(73), 4,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
  [210] = 8,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    STATE(79), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(73), 4,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
  [242] = 8,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    STATE(97), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(73), 4,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
  [274] = 8,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(48), 1,
      anon_sym_GT,
    ACTIONS(50), 1,
      sym_alias_operator,
    ACTIONS(52), 1,
      anon_sym_SLASH_GT,
    STATE(31), 1,
      sym_alias,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(32), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [301] = 8,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(50), 1,
      sym_alias_operator,
    ACTIONS(54), 1,
      anon_sym_GT,
    ACTIONS(56), 1,
      anon_sym_SLASH_GT,
    STATE(37), 1,
      sym_alias,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(38), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [328] = 3,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(58), 7,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_COLON,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ,
      anon_sym_SLASH_GT,
  [345] = 6,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    ACTIONS(66), 1,
      aux_sym_directive_token1,
    ACTIONS(68), 1,
      anon_sym_LF,
    ACTIONS(70), 1,
      anon_sym_LT,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(110), 3,
      sym_absolute_path,
      sym_relative_path,
      sym_constant,
  [367] = 3,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(72), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [383] = 3,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(76), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [399] = 8,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    ACTIONS(82), 1,
      anon_sym_DOLLAR,
    STATE(43), 1,
      sym_identifier,
    STATE(74), 1,
      sym_full_type_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(108), 1,
      sym_impl_operator,
    STATE(127), 1,
      sym_impl_ref,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [425] = 3,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(84), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [441] = 7,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(82), 1,
      anon_sym_DOLLAR,
    STATE(75), 1,
      sym_field,
    STATE(108), 1,
      sym_impl_operator,
    STATE(128), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(134), 2,
      sym_fields,
      sym_impl_ref,
  [465] = 3,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(88), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [481] = 3,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(92), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [497] = 3,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(96), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [513] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(102), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [532] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(104), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(30), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [551] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(106), 1,
      anon_sym_GT,
    ACTIONS(108), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(25), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [572] = 5,
    ACTIONS(110), 1,
      aux_sym_enum_token1,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(113), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(25), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [591] = 5,
    ACTIONS(115), 1,
      anon_sym_LT,
    ACTIONS(118), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [610] = 3,
    ACTIONS(120), 1,
      anon_sym_COLON_COLON,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(58), 5,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_LBRACE,
      sym_alias_operator,
      anon_sym_SLASH_GT,
  [625] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(122), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(36), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [644] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(124), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(22), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [663] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(124), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [682] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(126), 1,
      anon_sym_GT,
    ACTIONS(128), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(24), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [703] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(126), 1,
      anon_sym_GT,
    ACTIONS(128), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(25), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [724] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(130), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [743] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(132), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [762] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(134), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(34), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [781] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(104), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [800] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(136), 1,
      anon_sym_GT,
    ACTIONS(138), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(39), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [821] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(136), 1,
      anon_sym_GT,
    ACTIONS(138), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(25), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [842] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(140), 1,
      anon_sym_GT,
    ACTIONS(142), 1,
      anon_sym_SLASH_GT,
    STATE(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(25), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [863] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(144), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(41), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [882] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(134), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [901] = 5,
    ACTIONS(100), 1,
      anon_sym_LT,
    ACTIONS(132), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(33), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(101), 2,
      sym_empty_tag,
      sym_tag,
  [920] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(146), 5,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_LBRACE,
      sym_alias_operator,
      anon_sym_SLASH_GT,
  [932] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_field,
    STATE(128), 1,
      sym_identifier,
    STATE(139), 1,
      sym_fields,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [952] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    ACTIONS(152), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(80), 1,
      sym_field,
    STATE(128), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [972] = 6,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(80), 1,
      sym_field,
    STATE(128), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [992] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(158), 5,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_LBRACE,
      sym_alias_operator,
      anon_sym_SLASH_GT,
  [1004] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(10), 1,
      sym_full_type_identifier,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1021] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(160), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1032] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(162), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1043] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(140), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1060] = 5,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_fields_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1077] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(113), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1094] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1105] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(168), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1116] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(141), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1133] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1144] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(172), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1155] = 5,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(179), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(59), 1,
      aux_sym_fields_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1172] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(181), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1183] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(144), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1200] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1211] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1222] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1233] = 5,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(75), 1,
      sym_field,
    STATE(128), 1,
      sym_identifier,
    STATE(137), 1,
      sym_fields,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1250] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(189), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1261] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1272] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(11), 1,
      sym_full_type_identifier,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1289] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(130), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1306] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(131), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1323] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(132), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1340] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(133), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1357] = 3,
    ACTIONS(195), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(193), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
  [1370] = 5,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(75), 1,
      sym_field,
    STATE(116), 1,
      sym_fields,
    STATE(128), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1387] = 5,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_RBRACE,
    ACTIONS(201), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(52), 1,
      aux_sym_fields_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1404] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(145), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1421] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1432] = 5,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(43), 1,
      sym_identifier,
    STATE(85), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(112), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1449] = 3,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE_RBRACE,
  [1461] = 3,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE_RBRACE,
  [1473] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(209), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1483] = 4,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    STATE(90), 1,
      aux_sym_list_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1497] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(213), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1507] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(215), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1517] = 4,
    ACTIONS(80), 1,
      aux_sym_enum_token1,
    STATE(47), 1,
      sym_identifier,
    STATE(95), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1531] = 4,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(80), 1,
      sym_field,
    STATE(128), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1545] = 4,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      aux_sym_list_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1559] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(221), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1569] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(223), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1579] = 4,
    ACTIONS(225), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_list_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1593] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(230), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1603] = 3,
    ACTIONS(185), 1,
      anon_sym_LT_SLASH,
    ACTIONS(232), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1614] = 3,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    ACTIONS(236), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1625] = 3,
    ACTIONS(238), 1,
      anon_sym_struct,
    ACTIONS(240), 1,
      anon_sym_expr,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1636] = 3,
    ACTIONS(242), 1,
      aux_sym_enum_token1,
    STATE(95), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1647] = 3,
    ACTIONS(245), 1,
      anon_sym_DASH,
    STATE(51), 1,
      sym_bind_operator,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1658] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(228), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1667] = 3,
    ACTIONS(245), 1,
      anon_sym_DASH,
    STATE(56), 1,
      sym_bind_operator,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1678] = 3,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(96), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1689] = 3,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(98), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1700] = 3,
    ACTIONS(187), 1,
      anon_sym_LT_SLASH,
    ACTIONS(247), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1711] = 3,
    ACTIONS(203), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1722] = 3,
    ACTIONS(189), 1,
      anon_sym_LT_SLASH,
    ACTIONS(251), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1733] = 3,
    ACTIONS(183), 1,
      anon_sym_LT_SLASH,
    ACTIONS(253), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1744] = 3,
    ACTIONS(191), 1,
      anon_sym_LT_SLASH,
    ACTIONS(255), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1755] = 3,
    ACTIONS(160), 1,
      anon_sym_LT_SLASH,
    ACTIONS(257), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1766] = 3,
    ACTIONS(181), 1,
      anon_sym_LT_SLASH,
    ACTIONS(259), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1777] = 3,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(93), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1788] = 3,
    ACTIONS(46), 1,
      aux_sym_enum_token1,
    STATE(89), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1799] = 2,
    ACTIONS(261), 1,
      anon_sym_LF,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [1807] = 2,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1815] = 2,
    ACTIONS(265), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1823] = 2,
    ACTIONS(267), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1831] = 2,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1839] = 2,
    ACTIONS(271), 1,
      aux_sym_absolute_path_token1,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [1847] = 2,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1855] = 2,
    ACTIONS(275), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1863] = 2,
    ACTIONS(277), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1871] = 2,
    ACTIONS(279), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1879] = 2,
    ACTIONS(281), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1887] = 2,
    ACTIONS(283), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1895] = 2,
    ACTIONS(285), 1,
      aux_sym_string_token1,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [1903] = 2,
    ACTIONS(287), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1911] = 2,
    ACTIONS(289), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1919] = 2,
    ACTIONS(291), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1927] = 2,
    ACTIONS(293), 1,
      anon_sym_LF,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [1935] = 2,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1943] = 2,
    ACTIONS(297), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1951] = 2,
    ACTIONS(299), 1,
      aux_sym_directive_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1959] = 2,
    ACTIONS(301), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1967] = 2,
    ACTIONS(303), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1975] = 2,
    ACTIONS(305), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1983] = 2,
    ACTIONS(307), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1991] = 2,
    ACTIONS(309), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1999] = 2,
    ACTIONS(311), 1,
      aux_sym_relative_path_token1,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [2007] = 2,
    ACTIONS(120), 1,
      anon_sym_COLON_COLON,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2015] = 2,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2023] = 2,
    ACTIONS(315), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2031] = 2,
    ACTIONS(317), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2039] = 2,
    ACTIONS(319), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2047] = 2,
    ACTIONS(321), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2055] = 2,
    ACTIONS(323), 1,
      anon_sym_LF,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [2063] = 2,
    ACTIONS(325), 1,
      anon_sym_LF,
    ACTIONS(62), 2,
      sym_comment_multi,
      sym_comment_line,
  [2071] = 2,
    ACTIONS(327), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2079] = 2,
    ACTIONS(329), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 75,
  [SMALL_STATE(5)] = 110,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 178,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 274,
  [SMALL_STATE(11)] = 301,
  [SMALL_STATE(12)] = 328,
  [SMALL_STATE(13)] = 345,
  [SMALL_STATE(14)] = 367,
  [SMALL_STATE(15)] = 383,
  [SMALL_STATE(16)] = 399,
  [SMALL_STATE(17)] = 425,
  [SMALL_STATE(18)] = 441,
  [SMALL_STATE(19)] = 465,
  [SMALL_STATE(20)] = 481,
  [SMALL_STATE(21)] = 497,
  [SMALL_STATE(22)] = 513,
  [SMALL_STATE(23)] = 532,
  [SMALL_STATE(24)] = 551,
  [SMALL_STATE(25)] = 572,
  [SMALL_STATE(26)] = 591,
  [SMALL_STATE(27)] = 610,
  [SMALL_STATE(28)] = 625,
  [SMALL_STATE(29)] = 644,
  [SMALL_STATE(30)] = 663,
  [SMALL_STATE(31)] = 682,
  [SMALL_STATE(32)] = 703,
  [SMALL_STATE(33)] = 724,
  [SMALL_STATE(34)] = 743,
  [SMALL_STATE(35)] = 762,
  [SMALL_STATE(36)] = 781,
  [SMALL_STATE(37)] = 800,
  [SMALL_STATE(38)] = 821,
  [SMALL_STATE(39)] = 842,
  [SMALL_STATE(40)] = 863,
  [SMALL_STATE(41)] = 882,
  [SMALL_STATE(42)] = 901,
  [SMALL_STATE(43)] = 920,
  [SMALL_STATE(44)] = 932,
  [SMALL_STATE(45)] = 952,
  [SMALL_STATE(46)] = 972,
  [SMALL_STATE(47)] = 992,
  [SMALL_STATE(48)] = 1004,
  [SMALL_STATE(49)] = 1021,
  [SMALL_STATE(50)] = 1032,
  [SMALL_STATE(51)] = 1043,
  [SMALL_STATE(52)] = 1060,
  [SMALL_STATE(53)] = 1077,
  [SMALL_STATE(54)] = 1094,
  [SMALL_STATE(55)] = 1105,
  [SMALL_STATE(56)] = 1116,
  [SMALL_STATE(57)] = 1133,
  [SMALL_STATE(58)] = 1144,
  [SMALL_STATE(59)] = 1155,
  [SMALL_STATE(60)] = 1172,
  [SMALL_STATE(61)] = 1183,
  [SMALL_STATE(62)] = 1200,
  [SMALL_STATE(63)] = 1211,
  [SMALL_STATE(64)] = 1222,
  [SMALL_STATE(65)] = 1233,
  [SMALL_STATE(66)] = 1250,
  [SMALL_STATE(67)] = 1261,
  [SMALL_STATE(68)] = 1272,
  [SMALL_STATE(69)] = 1289,
  [SMALL_STATE(70)] = 1306,
  [SMALL_STATE(71)] = 1323,
  [SMALL_STATE(72)] = 1340,
  [SMALL_STATE(73)] = 1357,
  [SMALL_STATE(74)] = 1370,
  [SMALL_STATE(75)] = 1387,
  [SMALL_STATE(76)] = 1404,
  [SMALL_STATE(77)] = 1421,
  [SMALL_STATE(78)] = 1432,
  [SMALL_STATE(79)] = 1449,
  [SMALL_STATE(80)] = 1461,
  [SMALL_STATE(81)] = 1473,
  [SMALL_STATE(82)] = 1483,
  [SMALL_STATE(83)] = 1497,
  [SMALL_STATE(84)] = 1507,
  [SMALL_STATE(85)] = 1517,
  [SMALL_STATE(86)] = 1531,
  [SMALL_STATE(87)] = 1545,
  [SMALL_STATE(88)] = 1559,
  [SMALL_STATE(89)] = 1569,
  [SMALL_STATE(90)] = 1579,
  [SMALL_STATE(91)] = 1593,
  [SMALL_STATE(92)] = 1603,
  [SMALL_STATE(93)] = 1614,
  [SMALL_STATE(94)] = 1625,
  [SMALL_STATE(95)] = 1636,
  [SMALL_STATE(96)] = 1647,
  [SMALL_STATE(97)] = 1658,
  [SMALL_STATE(98)] = 1667,
  [SMALL_STATE(99)] = 1678,
  [SMALL_STATE(100)] = 1689,
  [SMALL_STATE(101)] = 1700,
  [SMALL_STATE(102)] = 1711,
  [SMALL_STATE(103)] = 1722,
  [SMALL_STATE(104)] = 1733,
  [SMALL_STATE(105)] = 1744,
  [SMALL_STATE(106)] = 1755,
  [SMALL_STATE(107)] = 1766,
  [SMALL_STATE(108)] = 1777,
  [SMALL_STATE(109)] = 1788,
  [SMALL_STATE(110)] = 1799,
  [SMALL_STATE(111)] = 1807,
  [SMALL_STATE(112)] = 1815,
  [SMALL_STATE(113)] = 1823,
  [SMALL_STATE(114)] = 1831,
  [SMALL_STATE(115)] = 1839,
  [SMALL_STATE(116)] = 1847,
  [SMALL_STATE(117)] = 1855,
  [SMALL_STATE(118)] = 1863,
  [SMALL_STATE(119)] = 1871,
  [SMALL_STATE(120)] = 1879,
  [SMALL_STATE(121)] = 1887,
  [SMALL_STATE(122)] = 1895,
  [SMALL_STATE(123)] = 1903,
  [SMALL_STATE(124)] = 1911,
  [SMALL_STATE(125)] = 1919,
  [SMALL_STATE(126)] = 1927,
  [SMALL_STATE(127)] = 1935,
  [SMALL_STATE(128)] = 1943,
  [SMALL_STATE(129)] = 1951,
  [SMALL_STATE(130)] = 1959,
  [SMALL_STATE(131)] = 1967,
  [SMALL_STATE(132)] = 1975,
  [SMALL_STATE(133)] = 1983,
  [SMALL_STATE(134)] = 1991,
  [SMALL_STATE(135)] = 1999,
  [SMALL_STATE(136)] = 2007,
  [SMALL_STATE(137)] = 2015,
  [SMALL_STATE(138)] = 2023,
  [SMALL_STATE(139)] = 2031,
  [SMALL_STATE(140)] = 2039,
  [SMALL_STATE(141)] = 2047,
  [SMALL_STATE(142)] = 2055,
  [SMALL_STATE(143)] = 2063,
  [SMALL_STATE(144)] = 2071,
  [SMALL_STATE(145)] = 2079,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_empty_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_empty_tag_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_type_identifier, 1, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_type_identifier, 2, 0, 4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7, 0, 9),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_impl, 7, 0, 11),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_impl, 7, 0, 11),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 5),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_impl, 6, 0, 8),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 8, 0, 13),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_tag, 5, 0, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 9, 0, 14),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_tag, 4, 0, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 7),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_value, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_tag, 3, 0, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 12),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 12),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 6),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 4, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 9, 0, 14),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_impl_ref, 2, 0, 10),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_ref, 2, 0, 10),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_type_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(136),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_tag, 3, 0, 3),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_tag, 4, 0, 3),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_tag, 5, 0, 3),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 7),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7, 0, 9),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 8, 0, 13),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [263] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_operator, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_impl_keyword, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_impl_keyword, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_full_type_identifier_repeat1, 2, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bind_operator, 2, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relative_path, 3, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_absolute_path, 3, 0, 0),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_type_ml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "type_ml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
