/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment_multi = 1,
  sym_comment_line = 2,
  sym_integer = 3,
  sym_float = 4,
  anon_sym_true = 5,
  anon_sym_false = 6,
  anon_sym_DQUOTE = 7,
  aux_sym_string_token1 = 8,
  aux_sym_enum_token1 = 9,
  sym_custom_enum = 10,
  anon_sym_POUND = 11,
  aux_sym_directive_token1 = 12,
  anon_sym_LF = 13,
  anon_sym_LT = 14,
  aux_sym_absolute_path_token1 = 15,
  anon_sym_GT = 16,
  aux_sym_relative_path_token1 = 17,
  anon_sym_DASH = 18,
  anon_sym_COLON_COLON = 19,
  anon_sym_LBRACK = 20,
  anon_sym_COMMA = 21,
  anon_sym_RBRACK = 22,
  anon_sym_DOLLAR = 23,
  anon_sym_COLON = 24,
  anon_sym_struct = 25,
  anon_sym_LBRACE = 26,
  anon_sym_RBRACE = 27,
  anon_sym_expr = 28,
  anon_sym_LBRACE_LBRACE = 29,
  anon_sym_RBRACE_RBRACE = 30,
  anon_sym_EQ = 31,
  sym_alias_operator = 32,
  anon_sym_SLASH_GT = 33,
  anon_sym_LT_SLASH = 34,
  sym_source_file = 35,
  sym_boolean = 36,
  sym_string = 37,
  sym_enum = 38,
  sym_directive = 39,
  sym_absolute_path = 40,
  sym_relative_path = 41,
  sym_constant = 42,
  sym_identifier = 43,
  sym_bind_operator = 44,
  sym_full_type_identifier = 45,
  sym_list = 46,
  sym_impl_ref = 47,
  sym_field_value = 48,
  sym_field = 49,
  sym_fields = 50,
  sym_struct_impl_keyword = 51,
  sym_struct_impl = 52,
  sym_expr_impl_keyword = 53,
  sym_expr_impl = 54,
  sym_expr = 55,
  sym_struct = 56,
  sym_attribute_value = 57,
  sym_attribute = 58,
  sym_alias = 59,
  sym_empty_tag = 60,
  sym_tag = 61,
  sym_element = 62,
  aux_sym_source_file_repeat1 = 63,
  aux_sym_full_type_identifier_repeat1 = 64,
  aux_sym_list_repeat1 = 65,
  aux_sym_fields_repeat1 = 66,
  aux_sym_empty_tag_repeat1 = 67,
  aux_sym_tag_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment_multi] = "comment_multi",
  [sym_comment_line] = "comment_line",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_enum_token1] = "enum_token1",
  [sym_custom_enum] = "custom_enum",
  [anon_sym_POUND] = "#",
  [aux_sym_directive_token1] = "directive_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_LT] = "<",
  [aux_sym_absolute_path_token1] = "absolute_path_token1",
  [anon_sym_GT] = ">",
  [aux_sym_relative_path_token1] = "relative_path_token1",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_COLON] = ":",
  [anon_sym_struct] = "struct",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_expr] = "expr",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_EQ] = "=",
  [sym_alias_operator] = "alias_operator",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [sym_source_file] = "source_file",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym_enum] = "enum",
  [sym_directive] = "directive",
  [sym_absolute_path] = "absolute_path",
  [sym_relative_path] = "relative_path",
  [sym_constant] = "constant",
  [sym_identifier] = "identifier",
  [sym_bind_operator] = "bind_operator",
  [sym_full_type_identifier] = "full_type_identifier",
  [sym_list] = "list",
  [sym_impl_ref] = "impl_ref",
  [sym_field_value] = "field_value",
  [sym_field] = "field",
  [sym_fields] = "fields",
  [sym_struct_impl_keyword] = "struct_impl_keyword",
  [sym_struct_impl] = "struct_impl",
  [sym_expr_impl_keyword] = "expr_impl_keyword",
  [sym_expr_impl] = "expr_impl",
  [sym_expr] = "expr",
  [sym_struct] = "struct",
  [sym_attribute_value] = "attribute_value",
  [sym_attribute] = "attribute",
  [sym_alias] = "alias",
  [sym_empty_tag] = "empty_tag",
  [sym_tag] = "tag",
  [sym_element] = "element",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_full_type_identifier_repeat1] = "full_type_identifier_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_fields_repeat1] = "fields_repeat1",
  [aux_sym_empty_tag_repeat1] = "empty_tag_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment_multi] = sym_comment_multi,
  [sym_comment_line] = sym_comment_line,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_enum_token1] = aux_sym_enum_token1,
  [sym_custom_enum] = sym_custom_enum,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_absolute_path_token1] = aux_sym_absolute_path_token1,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_relative_path_token1] = aux_sym_relative_path_token1,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_expr] = anon_sym_expr,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_alias_operator] = sym_alias_operator,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_source_file] = sym_source_file,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym_enum] = sym_enum,
  [sym_directive] = sym_directive,
  [sym_absolute_path] = sym_absolute_path,
  [sym_relative_path] = sym_relative_path,
  [sym_constant] = sym_constant,
  [sym_identifier] = sym_identifier,
  [sym_bind_operator] = sym_bind_operator,
  [sym_full_type_identifier] = sym_full_type_identifier,
  [sym_list] = sym_list,
  [sym_impl_ref] = sym_impl_ref,
  [sym_field_value] = sym_field_value,
  [sym_field] = sym_field,
  [sym_fields] = sym_fields,
  [sym_struct_impl_keyword] = sym_struct_impl_keyword,
  [sym_struct_impl] = sym_struct_impl,
  [sym_expr_impl_keyword] = sym_expr_impl_keyword,
  [sym_expr_impl] = sym_expr_impl,
  [sym_expr] = sym_expr,
  [sym_struct] = sym_struct,
  [sym_attribute_value] = sym_attribute_value,
  [sym_attribute] = sym_attribute,
  [sym_alias] = sym_alias,
  [sym_empty_tag] = sym_empty_tag,
  [sym_tag] = sym_tag,
  [sym_element] = sym_element,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_full_type_identifier_repeat1] = aux_sym_full_type_identifier_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_fields_repeat1] = aux_sym_fields_repeat1,
  [aux_sym_empty_tag_repeat1] = aux_sym_empty_tag_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment_multi] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_enum_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_custom_enum] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_absolute_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_relative_path_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_expr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_alias_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_absolute_path] = {
    .visible = true,
    .named = true,
  },
  [sym_relative_path] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_bind_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_full_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_impl_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_fields] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_impl_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_struct_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_impl_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_expr_impl] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_full_type_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fields_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_empty_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bind = 1,
  field_close_tag = 2,
  field_empty_tag = 3,
  field_field_identifier = 4,
  field_field_value = 5,
  field_fields = 6,
  field_identifier = 7,
  field_module = 8,
  field_name = 9,
  field_open_tag = 10,
  field_operator = 11,
  field_type = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bind] = "bind",
  [field_close_tag] = "close_tag",
  [field_empty_tag] = "empty_tag",
  [field_field_identifier] = "field_identifier",
  [field_field_value] = "field_value",
  [field_fields] = "fields",
  [field_identifier] = "identifier",
  [field_module] = "module",
  [field_name] = "name",
  [field_open_tag] = "open_tag",
  [field_operator] = "operator",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 2},
  [11] = {.index = 17, .length = 3},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 2},
  [14] = {.index = 24, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_type, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_empty_tag, 1},
  [3] =
    {field_module, 0},
    {field_type, 1},
  [5] =
    {field_name, 1},
    {field_value, 2},
  [7] =
    {field_identifier, 0},
    {field_value, 2},
  [9] =
    {field_close_tag, 4},
    {field_open_tag, 1},
  [11] =
    {field_identifier, 1},
    {field_operator, 0},
  [13] =
    {field_bind, 3},
    {field_identifier, 1},
  [15] =
    {field_close_tag, 5},
    {field_open_tag, 1},
  [17] =
    {field_bind, 3},
    {field_fields, 5},
    {field_identifier, 1},
  [20] =
    {field_field_identifier, 0},
    {field_field_value, 2},
  [22] =
    {field_close_tag, 6},
    {field_open_tag, 1},
  [24] =
    {field_close_tag, 7},
    {field_open_tag, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 21,
  [28] = 28,
  [29] = 29,
  [30] = 26,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 31,
  [35] = 32,
  [36] = 25,
  [37] = 37,
  [38] = 24,
  [39] = 23,
  [40] = 37,
  [41] = 22,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 62,
  [75] = 73,
  [76] = 48,
  [77] = 47,
  [78] = 64,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 49,
  [95] = 61,
  [96] = 79,
  [97] = 53,
  [98] = 68,
  [99] = 71,
  [100] = 100,
  [101] = 55,
  [102] = 60,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 109,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 120,
  [128] = 128,
  [129] = 121,
  [130] = 110,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
};

static const TSCharacterRange sym_custom_enum_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '#'}, {'%', '+'}, {'-', '.'}, {'0', '<'}, {'?', 'Z'},
  {'\\', '\\'}, {'^', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 50,
        '#', 67,
        '$', 89,
        ',', 87,
        '-', 84,
        '/', 4,
        ':', 90,
        '<', 71,
        '=', 99,
        '>', 77,
        '@', 100,
        '[', 86,
        ']', 88,
        'e', 26,
        'f', 12,
        's', 23,
        't', 18,
        '{', 93,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '"') ADVANCE(50);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '<') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 50,
        '$', 89,
        '-', 65,
        '/', 3,
        '[', 86,
        ']', 88,
        'f', 56,
        't', 60,
        '{', 93,
        '}', 94,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '-' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '>') ADVANCE(101);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '>') ADVANCE(77);
      if (lookahead == '@') ADVANCE(100);
      if (lookahead == '{') ADVANCE(92);
      if (lookahead == '}') ADVANCE(94);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(85);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(96);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 'x') ADVANCE(17);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(98);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '#', 67,
        '$', 89,
        ',', 87,
        '-', 83,
        '/', 4,
        ':', 90,
        '<', 70,
        '=', 99,
        '>', 77,
        '@', 100,
        ']', 88,
        '{', 92,
        '}', 95,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment_multi);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment_multi);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment_multi);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_comment_multi);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment_line);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '>') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comment_line);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(51);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'a') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'l') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'r') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (lookahead == 'u') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_enum_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_custom_enum);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_custom_enum);
      if ((!eof && set_contains(sym_custom_enum_character_set_1, 12, lookahead))) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(102);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '*') ADVANCE(73);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '*') ADVANCE(75);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '/') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '>') ADVANCE(5);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_absolute_path_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '*') ADVANCE(78);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead == '/') ADVANCE(80);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_relative_path_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(98);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_expr);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_alias_operator);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 28},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 28},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 28},
  [35] = {.lex_state = 28},
  [36] = {.lex_state = 28},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 28},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 28},
  [45] = {.lex_state = 28},
  [46] = {.lex_state = 28},
  [47] = {.lex_state = 28},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 28},
  [50] = {.lex_state = 28},
  [51] = {.lex_state = 28},
  [52] = {.lex_state = 28},
  [53] = {.lex_state = 28},
  [54] = {.lex_state = 28},
  [55] = {.lex_state = 28},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 28},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 28},
  [60] = {.lex_state = 28},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 28},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 28},
  [65] = {.lex_state = 28},
  [66] = {.lex_state = 28},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 28},
  [69] = {.lex_state = 28},
  [70] = {.lex_state = 28},
  [71] = {.lex_state = 28},
  [72] = {.lex_state = 28},
  [73] = {.lex_state = 28},
  [74] = {.lex_state = 28},
  [75] = {.lex_state = 28},
  [76] = {.lex_state = 28},
  [77] = {.lex_state = 28},
  [78] = {.lex_state = 28},
  [79] = {.lex_state = 28},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 28},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 28},
  [86] = {.lex_state = 28},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 28},
  [89] = {.lex_state = 28},
  [90] = {.lex_state = 28},
  [91] = {.lex_state = 28},
  [92] = {.lex_state = 28},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 28},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 28},
  [104] = {.lex_state = 28},
  [105] = {.lex_state = 28},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 28},
  [108] = {.lex_state = 28},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 54},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 9},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 10},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 28},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 6},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 8},
  [134] = {.lex_state = 28},
  [135] = {.lex_state = 8},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 28},
  [140] = {.lex_state = 2},
  [141] = {.lex_state = 28},
  [142] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment_multi] = ACTIONS(3),
    [sym_comment_line] = ACTIONS(3),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_expr] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_alias_operator] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(128),
    [sym_directive] = STATE(9),
    [sym_struct_impl_keyword] = STATE(108),
    [sym_struct_impl] = STATE(9),
    [sym_expr_impl_keyword] = STATE(104),
    [sym_expr_impl] = STATE(9),
    [sym_empty_tag] = STATE(49),
    [sym_tag] = STATE(49),
    [sym_element] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment_multi] = ACTIONS(3),
    [sym_comment_line] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_DOLLAR] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(85), 1,
      sym_attribute_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(13), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(89), 7,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_impl_ref,
      sym_expr,
      sym_struct,
  [44] = 10,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    STATE(106), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(56), 5,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_impl_ref,
  [83] = 10,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    STATE(106), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(56), 5,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_impl_ref,
  [122] = 9,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    STATE(87), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(56), 5,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_impl_ref,
  [158] = 9,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    STATE(106), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(56), 5,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_impl_ref,
  [194] = 9,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_enum_token1,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    STATE(82), 1,
      sym_field_value,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 3,
      sym_integer,
      sym_float,
      sym_custom_enum,
    STATE(56), 5,
      sym_boolean,
      sym_string,
      sym_enum,
      sym_list,
      sym_impl_ref,
  [230] = 9,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      anon_sym_POUND,
    ACTIONS(40), 1,
      anon_sym_LT,
    ACTIONS(43), 1,
      anon_sym_DOLLAR,
    STATE(104), 1,
      sym_expr_impl_keyword,
    STATE(108), 1,
      sym_struct_impl_keyword,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(49), 2,
      sym_empty_tag,
      sym_tag,
    STATE(8), 5,
      sym_directive,
      sym_struct_impl,
      sym_expr_impl,
      sym_element,
      aux_sym_source_file_repeat1,
  [264] = 9,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    STATE(104), 1,
      sym_expr_impl_keyword,
    STATE(108), 1,
      sym_struct_impl_keyword,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(49), 2,
      sym_empty_tag,
      sym_tag,
    STATE(8), 5,
      sym_directive,
      sym_struct_impl,
      sym_expr_impl,
      sym_element,
      aux_sym_source_file_repeat1,
  [298] = 3,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(48), 9,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_RBRACE_RBRACE,
      anon_sym_EQ,
      anon_sym_SLASH_GT,
  [317] = 8,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(54), 1,
      anon_sym_GT,
    ACTIONS(56), 1,
      sym_alias_operator,
    ACTIONS(58), 1,
      anon_sym_SLASH_GT,
    STATE(31), 1,
      sym_alias,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(32), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [344] = 8,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(56), 1,
      sym_alias_operator,
    ACTIONS(60), 1,
      anon_sym_GT,
    ACTIONS(62), 1,
      anon_sym_SLASH_GT,
    STATE(34), 1,
      sym_alias,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(35), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [371] = 3,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(64), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [387] = 3,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(68), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [403] = 3,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(72), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [419] = 3,
    ACTIONS(78), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(76), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [435] = 3,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(80), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [451] = 6,
    ACTIONS(86), 1,
      anon_sym_DQUOTE,
    ACTIONS(88), 1,
      aux_sym_directive_token1,
    ACTIONS(90), 1,
      anon_sym_LF,
    ACTIONS(92), 1,
      anon_sym_LT,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(142), 3,
      sym_absolute_path,
      sym_relative_path,
      sym_constant,
  [473] = 3,
    ACTIONS(96), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(94), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [489] = 3,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(98), 6,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
      anon_sym_SLASH_GT,
  [505] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(104), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(38), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [524] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(106), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(26), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [543] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(37), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [562] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [581] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(110), 1,
      anon_sym_GT,
    ACTIONS(112), 1,
      anon_sym_SLASH_GT,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(28), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [602] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(114), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [621] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(24), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [640] = 5,
    ACTIONS(118), 1,
      aux_sym_enum_token1,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(121), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(28), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [659] = 5,
    ACTIONS(123), 1,
      anon_sym_LT,
    ACTIONS(126), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [678] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(128), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [697] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(130), 1,
      anon_sym_GT,
    ACTIONS(132), 1,
      anon_sym_SLASH_GT,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(25), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [718] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(130), 1,
      anon_sym_GT,
    ACTIONS(132), 1,
      anon_sym_SLASH_GT,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(28), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [739] = 3,
    ACTIONS(134), 1,
      anon_sym_COLON_COLON,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(48), 5,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_LBRACE,
      sym_alias_operator,
      anon_sym_SLASH_GT,
  [754] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(136), 1,
      anon_sym_GT,
    ACTIONS(138), 1,
      anon_sym_SLASH_GT,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(36), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [775] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(136), 1,
      anon_sym_GT,
    ACTIONS(138), 1,
      anon_sym_SLASH_GT,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(28), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [796] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(140), 1,
      anon_sym_GT,
    ACTIONS(142), 1,
      anon_sym_SLASH_GT,
    STATE(114), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(28), 2,
      sym_attribute,
      aux_sym_empty_tag_repeat1,
  [817] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(106), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [836] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(144), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [855] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(144), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(40), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [874] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(146), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(29), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [893] = 5,
    ACTIONS(102), 1,
      anon_sym_LT,
    ACTIONS(146), 1,
      anon_sym_LT_SLASH,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    STATE(30), 2,
      sym_element,
      aux_sym_tag_repeat1,
    STATE(94), 2,
      sym_empty_tag,
      sym_tag,
  [912] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(148), 5,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_LBRACE,
      sym_alias_operator,
      anon_sym_SLASH_GT,
  [924] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_field,
    STATE(131), 1,
      sym_identifier,
    STATE(140), 1,
      sym_fields,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [944] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(152), 5,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_LBRACE,
      sym_alias_operator,
      anon_sym_SLASH_GT,
  [956] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(83), 1,
      sym_field,
    STATE(131), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [976] = 6,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
    ACTIONS(160), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(83), 1,
      sym_field,
    STATE(131), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [996] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(121), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1013] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(118), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1030] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(164), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1041] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(57), 1,
      sym_full_type_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1058] = 5,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(58), 1,
      sym_field,
    STATE(131), 1,
      sym_identifier,
    STATE(133), 1,
      sym_fields,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1075] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(166), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1086] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(168), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1097] = 5,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(58), 1,
      sym_field,
    STATE(131), 1,
      sym_identifier,
    STATE(136), 1,
      sym_fields,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1114] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(170), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1125] = 3,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(172), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE_RBRACE,
  [1138] = 5,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(58), 1,
      sym_field,
    STATE(116), 1,
      sym_fields,
    STATE(131), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1155] = 5,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(63), 1,
      aux_sym_fields_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1172] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1183] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(184), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1194] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(186), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1205] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(11), 1,
      sym_full_type_identifier,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1222] = 5,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(67), 1,
      aux_sym_fields_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1239] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(110), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1256] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(190), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1267] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(192), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1278] = 5,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(67), 1,
      aux_sym_fields_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1295] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1306] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(126), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1323] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(132), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1340] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1351] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(205), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1362] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(120), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1379] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(12), 1,
      sym_full_type_identifier,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1396] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(127), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1413] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(109), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1430] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(129), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1447] = 5,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(44), 1,
      sym_identifier,
    STATE(91), 1,
      aux_sym_full_type_identifier_repeat1,
    STATE(130), 1,
      sym_full_type_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1464] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(207), 4,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LT,
      anon_sym_DOLLAR,
  [1475] = 4,
    ACTIONS(209), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
    STATE(80), 1,
      aux_sym_list_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1489] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(214), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1499] = 3,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(216), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE_RBRACE,
  [1511] = 3,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE_RBRACE,
  [1523] = 4,
    ACTIONS(33), 1,
      anon_sym_RBRACK,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    STATE(80), 1,
      aux_sym_list_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1537] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(222), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1547] = 4,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(83), 1,
      sym_field,
    STATE(131), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1561] = 4,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RBRACK,
    STATE(84), 1,
      aux_sym_list_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1575] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(228), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1585] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(230), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1595] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(232), 3,
      aux_sym_enum_token1,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1605] = 4,
    ACTIONS(162), 1,
      aux_sym_enum_token1,
    STATE(42), 1,
      sym_identifier,
    STATE(107), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1619] = 3,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(90), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1630] = 3,
    ACTIONS(234), 1,
      anon_sym_struct,
    ACTIONS(236), 1,
      anon_sym_expr,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1641] = 3,
    ACTIONS(164), 1,
      anon_sym_LT_SLASH,
    ACTIONS(238), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1652] = 3,
    ACTIONS(186), 1,
      anon_sym_LT_SLASH,
    ACTIONS(240), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1663] = 3,
    ACTIONS(207), 1,
      anon_sym_LT_SLASH,
    ACTIONS(242), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1674] = 3,
    ACTIONS(168), 1,
      anon_sym_LT_SLASH,
    ACTIONS(244), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1685] = 3,
    ACTIONS(201), 1,
      anon_sym_LT_SLASH,
    ACTIONS(246), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1696] = 3,
    ACTIONS(203), 1,
      anon_sym_LT_SLASH,
    ACTIONS(248), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1707] = 3,
    ACTIONS(250), 1,
      anon_sym_DASH,
    STATE(69), 1,
      sym_bind_operator,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1718] = 3,
    ACTIONS(170), 1,
      anon_sym_LT_SLASH,
    ACTIONS(252), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1729] = 3,
    ACTIONS(184), 1,
      anon_sym_LT_SLASH,
    ACTIONS(254), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1740] = 3,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(16), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1751] = 3,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(105), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1762] = 3,
    ACTIONS(250), 1,
      anon_sym_DASH,
    STATE(70), 1,
      sym_bind_operator,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1773] = 2,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
    ACTIONS(212), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1782] = 3,
    ACTIONS(256), 1,
      aux_sym_enum_token1,
    STATE(107), 1,
      aux_sym_full_type_identifier_repeat1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1793] = 3,
    ACTIONS(52), 1,
      aux_sym_enum_token1,
    STATE(100), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1804] = 2,
    ACTIONS(259), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1812] = 2,
    ACTIONS(261), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1820] = 2,
    ACTIONS(263), 1,
      anon_sym_LF,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
  [1828] = 2,
    ACTIONS(265), 1,
      aux_sym_string_token1,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
  [1836] = 2,
    ACTIONS(267), 1,
      anon_sym_LF,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
  [1844] = 2,
    ACTIONS(269), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1852] = 2,
    ACTIONS(271), 1,
      aux_sym_absolute_path_token1,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
  [1860] = 2,
    ACTIONS(273), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1868] = 2,
    ACTIONS(275), 1,
      aux_sym_relative_path_token1,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
  [1876] = 2,
    ACTIONS(277), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1884] = 2,
    ACTIONS(279), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1892] = 2,
    ACTIONS(281), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1900] = 2,
    ACTIONS(283), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1908] = 2,
    ACTIONS(285), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1916] = 2,
    ACTIONS(287), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1924] = 2,
    ACTIONS(289), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1932] = 2,
    ACTIONS(134), 1,
      anon_sym_COLON_COLON,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1940] = 2,
    ACTIONS(291), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1948] = 2,
    ACTIONS(293), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1956] = 2,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1964] = 2,
    ACTIONS(297), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1972] = 2,
    ACTIONS(299), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1980] = 2,
    ACTIONS(301), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1988] = 2,
    ACTIONS(303), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [1996] = 2,
    ACTIONS(305), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2004] = 2,
    ACTIONS(307), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2012] = 2,
    ACTIONS(309), 1,
      aux_sym_directive_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2020] = 2,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2028] = 2,
    ACTIONS(313), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2036] = 2,
    ACTIONS(315), 1,
      anon_sym_LF,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
  [2044] = 2,
    ACTIONS(317), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2052] = 2,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2060] = 2,
    ACTIONS(321), 1,
      aux_sym_enum_token1,
    ACTIONS(3), 2,
      sym_comment_multi,
      sym_comment_line,
  [2068] = 2,
    ACTIONS(323), 1,
      anon_sym_LF,
    ACTIONS(84), 2,
      sym_comment_multi,
      sym_comment_line,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 44,
  [SMALL_STATE(4)] = 83,
  [SMALL_STATE(5)] = 122,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 194,
  [SMALL_STATE(8)] = 230,
  [SMALL_STATE(9)] = 264,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 317,
  [SMALL_STATE(12)] = 344,
  [SMALL_STATE(13)] = 371,
  [SMALL_STATE(14)] = 387,
  [SMALL_STATE(15)] = 403,
  [SMALL_STATE(16)] = 419,
  [SMALL_STATE(17)] = 435,
  [SMALL_STATE(18)] = 451,
  [SMALL_STATE(19)] = 473,
  [SMALL_STATE(20)] = 489,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 524,
  [SMALL_STATE(23)] = 543,
  [SMALL_STATE(24)] = 562,
  [SMALL_STATE(25)] = 581,
  [SMALL_STATE(26)] = 602,
  [SMALL_STATE(27)] = 621,
  [SMALL_STATE(28)] = 640,
  [SMALL_STATE(29)] = 659,
  [SMALL_STATE(30)] = 678,
  [SMALL_STATE(31)] = 697,
  [SMALL_STATE(32)] = 718,
  [SMALL_STATE(33)] = 739,
  [SMALL_STATE(34)] = 754,
  [SMALL_STATE(35)] = 775,
  [SMALL_STATE(36)] = 796,
  [SMALL_STATE(37)] = 817,
  [SMALL_STATE(38)] = 836,
  [SMALL_STATE(39)] = 855,
  [SMALL_STATE(40)] = 874,
  [SMALL_STATE(41)] = 893,
  [SMALL_STATE(42)] = 912,
  [SMALL_STATE(43)] = 924,
  [SMALL_STATE(44)] = 944,
  [SMALL_STATE(45)] = 956,
  [SMALL_STATE(46)] = 976,
  [SMALL_STATE(47)] = 996,
  [SMALL_STATE(48)] = 1013,
  [SMALL_STATE(49)] = 1030,
  [SMALL_STATE(50)] = 1041,
  [SMALL_STATE(51)] = 1058,
  [SMALL_STATE(52)] = 1075,
  [SMALL_STATE(53)] = 1086,
  [SMALL_STATE(54)] = 1097,
  [SMALL_STATE(55)] = 1114,
  [SMALL_STATE(56)] = 1125,
  [SMALL_STATE(57)] = 1138,
  [SMALL_STATE(58)] = 1155,
  [SMALL_STATE(59)] = 1172,
  [SMALL_STATE(60)] = 1183,
  [SMALL_STATE(61)] = 1194,
  [SMALL_STATE(62)] = 1205,
  [SMALL_STATE(63)] = 1222,
  [SMALL_STATE(64)] = 1239,
  [SMALL_STATE(65)] = 1256,
  [SMALL_STATE(66)] = 1267,
  [SMALL_STATE(67)] = 1278,
  [SMALL_STATE(68)] = 1295,
  [SMALL_STATE(69)] = 1306,
  [SMALL_STATE(70)] = 1323,
  [SMALL_STATE(71)] = 1340,
  [SMALL_STATE(72)] = 1351,
  [SMALL_STATE(73)] = 1362,
  [SMALL_STATE(74)] = 1379,
  [SMALL_STATE(75)] = 1396,
  [SMALL_STATE(76)] = 1413,
  [SMALL_STATE(77)] = 1430,
  [SMALL_STATE(78)] = 1447,
  [SMALL_STATE(79)] = 1464,
  [SMALL_STATE(80)] = 1475,
  [SMALL_STATE(81)] = 1489,
  [SMALL_STATE(82)] = 1499,
  [SMALL_STATE(83)] = 1511,
  [SMALL_STATE(84)] = 1523,
  [SMALL_STATE(85)] = 1537,
  [SMALL_STATE(86)] = 1547,
  [SMALL_STATE(87)] = 1561,
  [SMALL_STATE(88)] = 1575,
  [SMALL_STATE(89)] = 1585,
  [SMALL_STATE(90)] = 1595,
  [SMALL_STATE(91)] = 1605,
  [SMALL_STATE(92)] = 1619,
  [SMALL_STATE(93)] = 1630,
  [SMALL_STATE(94)] = 1641,
  [SMALL_STATE(95)] = 1652,
  [SMALL_STATE(96)] = 1663,
  [SMALL_STATE(97)] = 1674,
  [SMALL_STATE(98)] = 1685,
  [SMALL_STATE(99)] = 1696,
  [SMALL_STATE(100)] = 1707,
  [SMALL_STATE(101)] = 1718,
  [SMALL_STATE(102)] = 1729,
  [SMALL_STATE(103)] = 1740,
  [SMALL_STATE(104)] = 1751,
  [SMALL_STATE(105)] = 1762,
  [SMALL_STATE(106)] = 1773,
  [SMALL_STATE(107)] = 1782,
  [SMALL_STATE(108)] = 1793,
  [SMALL_STATE(109)] = 1804,
  [SMALL_STATE(110)] = 1812,
  [SMALL_STATE(111)] = 1820,
  [SMALL_STATE(112)] = 1828,
  [SMALL_STATE(113)] = 1836,
  [SMALL_STATE(114)] = 1844,
  [SMALL_STATE(115)] = 1852,
  [SMALL_STATE(116)] = 1860,
  [SMALL_STATE(117)] = 1868,
  [SMALL_STATE(118)] = 1876,
  [SMALL_STATE(119)] = 1884,
  [SMALL_STATE(120)] = 1892,
  [SMALL_STATE(121)] = 1900,
  [SMALL_STATE(122)] = 1908,
  [SMALL_STATE(123)] = 1916,
  [SMALL_STATE(124)] = 1924,
  [SMALL_STATE(125)] = 1932,
  [SMALL_STATE(126)] = 1940,
  [SMALL_STATE(127)] = 1948,
  [SMALL_STATE(128)] = 1956,
  [SMALL_STATE(129)] = 1964,
  [SMALL_STATE(130)] = 1972,
  [SMALL_STATE(131)] = 1980,
  [SMALL_STATE(132)] = 1988,
  [SMALL_STATE(133)] = 1996,
  [SMALL_STATE(134)] = 2004,
  [SMALL_STATE(135)] = 2012,
  [SMALL_STATE(136)] = 2020,
  [SMALL_STATE(137)] = 2028,
  [SMALL_STATE(138)] = 2036,
  [SMALL_STATE(139)] = 2044,
  [SMALL_STATE(140)] = 2052,
  [SMALL_STATE(141)] = 2060,
  [SMALL_STATE(142)] = 2068,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_enum, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_impl_ref, 2, 0, 8),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_impl_ref, 2, 0, 8),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(117),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_empty_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_empty_tag_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_type_identifier, 2, 0, 4),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_type_identifier, 1, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 3, 0, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_tag, 5, 0, 3),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 7),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_value, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_value, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fields, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fields, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_impl, 6, 0, 9),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7, 0, 10),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_tag, 3, 0, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_impl, 7, 0, 11),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_impl, 7, 0, 11),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fields_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 8, 0, 13),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 9, 0, 14),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 4, 0, 5),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_tag, 4, 0, 3),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 4, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 12),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 12),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 6),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_tag, 3, 0, 3),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_tag, 4, 0, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_tag, 5, 0, 3),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 8, 0, 13),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 9, 0, 14),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 7),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7, 0, 10),
  [256] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_full_type_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_relative_path, 3, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_absolute_path, 3, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bind_operator, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [295] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_full_type_identifier_repeat1, 2, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct_impl_keyword, 2, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr_impl_keyword, 2, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_type_ml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "type_ml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
